apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: artist-api
  description: Retrieve artist details
spec:
  type: openapi
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Artist API
      license:
        name: MIT
    servers:
      - url: https://rio-api.pie.apple.com/v1
    paths:
      /projects/sample-harshal-sample-rio:
        get:
          summary: List all projects
        parameters:
         - description: A valid user access token or your client credentials.
           in: header
           name: X-RIO-API-EMAIL
           required: true
           schema:
             type: string
         - description: A valid user access token or your client credentials.
           in: header
           name: X-RIO-API-TOKEN
           required: true
           schema:
             type: string
        responses:
          '200':
            description: A paged array of pets
            headers:
              x-next:
                description: A link to the next page of responses
                schema:
                type: string
            content:
              application/json:    
                schema:
                  $ref: "#/components/schemas/Pet"
    components:
      schemas:
        Pet:
          type: object
          required:
            - id       
          properties:
            id:
              type: string
        Pets:
          type: array
          items:
             $ref: "#/components/schemas/Pet"
    
